// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	model "ad_integration/internal/auth/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserData is a mock of UserData interface.
type MockUserData struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataMockRecorder
}

// MockUserDataMockRecorder is the mock recorder for MockUserData.
type MockUserDataMockRecorder struct {
	mock *MockUserData
}

// NewMockUserData creates a new mock instance.
func NewMockUserData(ctrl *gomock.Controller) *MockUserData {
	mock := &MockUserData{ctrl: ctrl}
	mock.recorder = &MockUserDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserData) EXPECT() *MockUserDataMockRecorder {
	return m.recorder
}

// GetAttr mocks base method.
func (m *MockUserData) GetAttr() map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttr")
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// GetAttr indicates an expected call of GetAttr.
func (mr *MockUserDataMockRecorder) GetAttr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttr", reflect.TypeOf((*MockUserData)(nil).GetAttr))
}

// GetDN mocks base method.
func (m *MockUserData) GetDN() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDN")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDN indicates an expected call of GetDN.
func (mr *MockUserDataMockRecorder) GetDN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDN", reflect.TypeOf((*MockUserData)(nil).GetDN))
}

// MockIdentityProvider is a mock of IdentityProvider interface.
type MockIdentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderMockRecorder
}

// MockIdentityProviderMockRecorder is the mock recorder for MockIdentityProvider.
type MockIdentityProviderMockRecorder struct {
	mock *MockIdentityProvider
}

// NewMockIdentityProvider creates a new mock instance.
func NewMockIdentityProvider(ctrl *gomock.Controller) *MockIdentityProvider {
	mock := &MockIdentityProvider{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityProvider) EXPECT() *MockIdentityProviderMockRecorder {
	return m.recorder
}

// BindUser mocks base method.
func (m *MockIdentityProvider) BindUser(login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindUser", login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindUser indicates an expected call of BindUser.
func (mr *MockIdentityProviderMockRecorder) BindUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindUser", reflect.TypeOf((*MockIdentityProvider)(nil).BindUser), login, password)
}

// Search mocks base method.
func (m *MockIdentityProvider) Search(ctx context.Context, filter string, attributes []string) (*model.RawUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, filter, attributes)
	ret0, _ := ret[0].(*model.RawUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIdentityProviderMockRecorder) Search(ctx, filter, attributes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIdentityProvider)(nil).Search), ctx, filter, attributes)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// RefreshUserRoles mocks base method.
func (m *MockUserRepository) RefreshUserRoles(ctx context.Context, userID int, groups []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshUserRoles", ctx, userID, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshUserRoles indicates an expected call of RefreshUserRoles.
func (mr *MockUserRepositoryMockRecorder) RefreshUserRoles(ctx, userID, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshUserRoles", reflect.TypeOf((*MockUserRepository)(nil).RefreshUserRoles), ctx, userID, groups)
}

// SyncGroups mocks base method.
func (m *MockUserRepository) SyncGroups(ctx context.Context, groups []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGroups", ctx, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncGroups indicates an expected call of SyncGroups.
func (mr *MockUserRepositoryMockRecorder) SyncGroups(ctx, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGroups", reflect.TypeOf((*MockUserRepository)(nil).SyncGroups), ctx, groups)
}

// SyncUser mocks base method.
func (m *MockUserRepository) SyncUser(ctx context.Context, login, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUser", ctx, login, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncUser indicates an expected call of SyncUser.
func (mr *MockUserRepositoryMockRecorder) SyncUser(ctx, login, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUser", reflect.TypeOf((*MockUserRepository)(nil).SyncUser), ctx, login, email)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithInTransaction mocks base method.
func (m *MockTxManager) WithInTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithInTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithInTransaction indicates an expected call of WithInTransaction.
func (mr *MockTxManagerMockRecorder) WithInTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInTransaction", reflect.TypeOf((*MockTxManager)(nil).WithInTransaction), ctx, fn)
}
