// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	model "ad_integration/internal/auth/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// RefreshUserRoles mocks base method.
func (m *MockUserRepository) RefreshUserRoles(ctx context.Context, userID int, groups []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshUserRoles", ctx, userID, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshUserRoles indicates an expected call of RefreshUserRoles.
func (mr *MockUserRepositoryMockRecorder) RefreshUserRoles(ctx, userID, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshUserRoles", reflect.TypeOf((*MockUserRepository)(nil).RefreshUserRoles), ctx, userID, groups)
}

// SyncGroups mocks base method.
func (m *MockUserRepository) SyncGroups(ctx context.Context, groups []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGroups", ctx, groups)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncGroups indicates an expected call of SyncGroups.
func (mr *MockUserRepositoryMockRecorder) SyncGroups(ctx, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGroups", reflect.TypeOf((*MockUserRepository)(nil).SyncGroups), ctx, groups)
}

// SyncUser mocks base method.
func (m *MockUserRepository) SyncUser(ctx context.Context, login, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUser", ctx, login, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncUser indicates an expected call of SyncUser.
func (mr *MockUserRepositoryMockRecorder) SyncUser(ctx, login, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUser", reflect.TypeOf((*MockUserRepository)(nil).SyncUser), ctx, login, email)
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// WithInTransaction mocks base method.
func (m *MockTransactionManager) WithInTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithInTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithInTransaction indicates an expected call of WithInTransaction.
func (mr *MockTransactionManagerMockRecorder) WithInTransaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInTransaction", reflect.TypeOf((*MockTransactionManager)(nil).WithInTransaction), ctx, fn)
}
